
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-13
owner: ucsb-cs156-f25
repo_name: team02-f25-13
pull_requests: [{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-copy-backend-for-recRequest","number":66,"title":"yy - copy backend CRUD operation from team01 for the recRequest table","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/66"},{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-create-fixtures-Articles","number":65,"title":"n-ornelas - Created fixtures for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/65"},{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-copy-backend-Articles","number":64,"title":"n-ornelas - Copied backend CRUD API files for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/64"},{"author":{"id":"U_kgDOCVHjrA","is_bot":false,"login":"yoonseo642","name":""},"headRefName":"ys-copy-files-backend-ucsbdiningcommonsmenuitem","number":63,"title":"copy files for backend UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/63"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"Hao-copy-backend-for-helpRequest","number":62,"title":"Copied backend files from team01 to team02","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/62"},{"author":{"id":"U_kgDOCML-cA","is_bot":false,"login":"amyli2027","name":"Amy Li"},"headRefName":"amyli2027-AddTableToReadme","number":61,"title":"Update README.md with team member roles","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/61"}]
