
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-13
owner: ucsb-cs156-f25
repo_name: team02-f25-13
pull_requests: [{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"team03-lemonacl-end2end","number":117,"title":"HelpRequest end-to-end Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/117"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"Hao-form-test-bugs","number":116,"title":"HelpRequest Form testids and test","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/116"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"team03-lemonacl","number":115,"title":"Created two integration tests for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/115"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-form","number":106,"title":"Yy add form for rec request","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/106"},{"author":{"id":"U_kgDOCVHjrA","is_bot":false,"login":"yoonseo642","name":""},"headRefName":"ys-ucsbdiningcommonsmenuitem-placeholder-page","number":91,"title":"Ys ucsbdiningcommonsmenuitem placeholder page","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/91"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-fixtures","number":71,"title":"Yy add javascript rec request fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/71"}]
