
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-13
owner: ucsb-cs156-f25
repo_name: team02-f25-13
pull_requests: [{"author":{"id":"U_kgDOCsAPpQ","is_bot":false,"login":"sidushdid","name":""},"headRefName":"sidushdid-itegration-test","number":122,"title":"added integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/122"},{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-team03-Articles-end2end","number":121,"title":"n-ornelas - Added end-2-end tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/121"},{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-team03-Articles-tests","number":120,"title":"n-ornelas - Added integration tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/120"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-placeholder-pages","number":119,"title":"Yy- add rec request placeholder pages (index, edit, create)","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/119"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-table","number":118,"title":"Yy rec request table","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/118"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"team03-lemonacl-end2end","number":117,"title":"HelpRequest end-to-end Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/117"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-form","number":106,"title":"Yy add form for rec request","url":"https://github.com/ucsb-cs156-f25/team02-f25-13/pull/106"}]
