package edu.ucsb.cs156.example.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity(name = "MenuItemReview")
public class MenuItemReview {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY) // autogenerated id
  private Long id;

  private Long itemId;
  private String reviewerEmail;

  @Min(value = 1, message = "Stars must be between 1 and 5")
  @Max(value = 5, message = "Stars must be between 1 and 5")
  private int stars;

  private LocalDateTime dateReviewed;
  private String comments;
}
